<a href="https://colab.research.google.com/github/Taryn-Cail/Predicting-Dementia-Diagnosis-Using-Lifestyle-and-Health-Factors/blob/main/CS4403_Project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Predicting Dementia Diagnosis Using Lifestyle and Health Factors

CS4403 Project Data Cleaning and Preprocessing
Taryn Cail - 3756155

# Data Cleaning and Preprocessing

## Importing Data

In [ ]:
#imports for processing the data
import pandas as pd
import numpy as np
import glob
from google.colab import drive
from google.colab import data_table
data_table.enable_dataframe_formatter()

In [ ]:
#upload csv files from google drive
drive.mount('/content/drive')
df1 = pd.read_csv('/content/drive/MyDrive/data/alzheimers_disease_data.csv')
df2 = pd.read_csv('/content/drive/MyDrive/data/dementia_patients_health_data.csv')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

df1 = alzheimers_disease_data.csv

df2 = dementia_patients_health_data.csv

##Original Information

In [ ]:
# print all the data frames to compare and contrast information
df1.info()

df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2149 entries, 0 to 2148
Data columns (total 35 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   PatientID                  2149 non-null   int64
 1   Age                        2149 non-null   int64
 2   Gender                     2149 non-null   int64
 3   Ethnicity                  2149 non-null   int64
 4   EducationLevel             2149 non-null   int64
 5   BMI                        2149 non-null   float64
 6   Smoking                    2149 non-null   int64
 7   AlcoholConsumption         2149 non-null   float64
 8   PhysicalActivity           2149 non-null   float64
 9   DietQuality                2149 non-null   float64
 10  SleepQuality               2149 non-null   float64
 11  FamilyHistoryAlzheimers    2149 non-null   int64
 12  CardiovascularDisease      2149 non-null   int64
 13  Diabetes                   2149 non-null   int64
 14  Depression                 2149 non-null   int64
 15  HeadInjury                 2149 non-null   int64
 16  Hypertension               2149 non-null   int64
 17  SystolicBP                 2149 non-null   int64
 18  DiastolicBP                2149 non-null   int64
 19  CholesterolTotal           2149 non-null   float64
 20  CholesterolLDL             2149 non-null   float64
 21  CholesterolHDL             2149 non-null   float64
 22  CholesterolTriglycerides   2149 non-null   float64
 23  MMSE                       2149 non-null   float64
 24  FunctionalAssessment       2149 non-null   float64
 25  MemoryComplaints           2149 non-null   int64
 26  BehavioralProblems         2149 non-null   int64
 27  ADL                        2149 non-null   float64
 28  Confusion                  2149 non-null   int64
 29  Disorientation             2149 non-null   int64
 30  PersonalityChanges         2149 non-null   int64
 31  DifficultyCompletingTasks  2149 non-null   int64
 32  Forgetfulness              2149 non-null   int64
 33  Diagnosis                  2149 non-null   int64
 34  DoctorInCharge             2149 non-null   object
dtypes: float64(12), int64(22), object(1)
memory usage: 587.7+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 24 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Diabetic                   1000 non-null   int64
 1   AlcoholLevel               1000 non-null   float64
 2   HeartRate                  1000 non-null   int64
 3   BloodOxygenLevel           1000 non-null   float64
 4   BodyTemperature            1000 non-null   float64
 5   Weight                     1000 non-null   float64
 6   MRI_Delay                  1000 non-null   float64
 7   Prescription               485 non-null    object
 8   Dosage in mg               485 non-null    float64
 9   Age                        1000 non-null   int64
 10  Education_Level            1000 non-null   object
 11  Dominant_Hand              1000 non-null   object
 12  Gender                     1000 non-null   object
 13  Family_History             1000 non-null   object
 14  Smoking_Status             1000 non-null   object
 15  APOE_ε4                    1000 non-null   object
 16  Physical_Activity          1000 non-null   object
 17  Depression_Status          1000 non-null   object
 18  Cognitive_Test_Scores      1000 non-null   int64
 19  Medication_History         1000 non-null   object
 20  Nutrition_Diet             1000 non-null   object
 21  Sleep_Quality              1000 non-null   object
 22  Chronic_Health_Conditions  821 non-null    object
 23  Dementia                   1000 non-null   int64
dtypes: float64(6), int64(5), object(13)
memory usage: 187.6+ KB

##Removing Columns

In [ ]:
# keeping these columns from df1
keep_cols_df1 = [
 'Age',
 'Gender',
 'EducationLevel',
 'Smoking',
 'AlcoholConsumption',
 'PhysicalActivity',
 'DietQuality',
 'SleepQuality',
 'FamilyHistoryAlzheimers',
 'CardiovascularDisease',
 'Diabetes',
 'Depression',
 'Hypertension',
 'Diagnosis'
]

In [ ]:
#keeping only these columns from df1
df1 = df1[keep_cols_df1]

In [ ]:
df1.columns.tolist()
df1.head()

,Age,Gender,EducationLevel,Smoking,AlcoholConsumption,PhysicalActivity,DietQuality,SleepQuality,FamilyHistoryAlzheimers,CardiovascularDisease,Diabetes,Depression,Hypertension,Diagnosis
0,73,0,2,0,13.297218,6.327112,1.347214,9.025679,0,0,1,1,0,0
1,89,0,0,0,4.542524,7.619885,0.518767,7.151293,0,0,0,0,0,0
2,73,0,1,0,19.555085,7.844988,1.826335,9.673574,1,0,0,0,0,0
3,74,1,1,1,12.209266,8.428001,7.435604,8.392554,0,0,0,0,0,0
4,89,0,0,0,18.454356,6.310461,0.795498,5.597238,0,0,0,0,0,0

In [ ]:
#Keep these columns for df2
keep_cols_df2 = [
    'Diabetic',
    'AlcoholLevel',
    'Age',
    'Education_Level',
    'Gender',
    'Family_History',
    'Smoking_Status',
    'Physical_Activity',
    'Depression_Status',
    'Nutrition_Diet',
    'Sleep_Quality',
    'Chronic_Health_Conditions',
    'Dementia'
]

In [ ]:
df2 = df2[keep_cols_df2]

In [ ]:
df2.columns.tolist()
df2.head()

,Diabetic,AlcoholLevel,Age,Education_Level,Gender,Family_History,Smoking_Status,Physical_Activity,Depression_Status,Nutrition_Diet,Sleep_Quality,Chronic_Health_Conditions,Dementia
0,1,0.084974,60,Primary School,Female,No,Current Smoker,Sedentary,No,Low-Carb Diet,Poor,Diabetes,0
1,0,0.016973,61,Secondary School,Male,No,Former Smoker,Moderate Activity,No,Low-Carb Diet,Poor,Heart Disease,1
2,0,0.009000,69,Primary School,Male,Yes,Former Smoker,Moderate Activity,No,Mediterranean Diet,Poor,Heart Disease,0
3,0,0.086437,78,Secondary School,Female,Yes,Never Smoked,Mild Activity,Yes,Balanced Diet,Poor,Hypertension,1
4,1,0.150747,77,Secondary School,Male,Yes,Never Smoked,Mild Activity,No,Low-Carb Diet,Good,Diabetes,1

##Altering Chronic Disease Column

manipulating chronic disease column in df2 to have three seperate columns for heart disease, diabetes and hypertension,ignoring any other conditions

In [ ]:
#going through the chronic health conditions column and seperating it
#ASSUMING that NAN values are 0
df2['Chronic_Diabetes'] = df2['Chronic_Health_Conditions'].str.contains('Diabetes', case=False, na=False).astype(int)

df2['Hypertension'] = df2['Chronic_Health_Conditions'].str.contains('Hypertension', case=False, na=False).astype(int)

df2['CardiovascularDisease'] = df2['Chronic_Health_Conditions'].str.contains('Heart', case=False, na=False).astype(int)

In [ ]:
# dropping health conditions column
df2 = df2.drop(columns=['Chronic_Health_Conditions'])

In [ ]:
#displaying new dataset 2
df2.head()

,Diabetic,AlcoholLevel,Age,Education_Level,Gender,Family_History,Smoking_Status,Physical_Activity,Depression_Status,Nutrition_Diet,Sleep_Quality,Dementia,Chronic_Diabetes,Hypertension,CardiovascularDisease
0,1,0.084974,60,Primary School,Female,No,Current Smoker,Sedentary,No,Low-Carb Diet,Poor,0,1,0,0
1,0,0.016973,61,Secondary School,Male,No,Former Smoker,Moderate Activity,No,Low-Carb Diet,Poor,1,0,0,1
2,0,0.009000,69,Primary School,Male,Yes,Former Smoker,Moderate Activity,No,Mediterranean Diet,Poor,0,0,0,1
3,0,0.086437,78,Secondary School,Female,Yes,Never Smoked,Mild Activity,Yes,Balanced Diet,Poor,1,0,1,0
4,1,0.150747,77,Secondary School,Male,Yes,Never Smoked,Mild Activity,No,Low-Carb Diet,Good,1,1,0,0

In [ ]:
# making sure both columns are the same
(df2['Diabetic'] == df2['Chronic_Diabetes']).value_counts()

True    1000
Name: count, dtype: int64

In [ ]:
#merging the two columns
df2['Diabetic'] = df2[['Diabetic', 'Chronic_Diabetes']].max(axis=1)

In [ ]:
#dropping the chronic diabetes row
df2 = df2.drop(columns=['Chronic_Diabetes'])

In [ ]:
# Renaming diabetic column
df2.rename(columns={'Diabetic': 'Diabetes'}, inplace=True)

In [ ]:
#displaying new dataset 2
df2.head()

,Diabetes,AlcoholLevel,Age,Education_Level,Gender,Family_History,Smoking_Status,Physical_Activity,Depression_Status,Nutrition_Diet,Sleep_Quality,Dementia,Hypertension,CardiovascularDisease
0,1,0.084974,60,Primary School,Female,No,Current Smoker,Sedentary,No,Low-Carb Diet,Poor,0,0,0
1,0,0.016973,61,Secondary School,Male,No,Former Smoker,Moderate Activity,No,Low-Carb Diet,Poor,1,0,1
2,0,0.009000,69,Primary School,Male,Yes,Former Smoker,Moderate Activity,No,Mediterranean Diet,Poor,0,0,1
3,0,0.086437,78,Secondary School,Female,Yes,Never Smoked,Mild Activity,Yes,Balanced Diet,Poor,1,1,0
4,1,0.150747,77,Secondary School,Male,Yes,Never Smoked,Mild Activity,No,Low-Carb Diet,Good,1,0,0

##Sorting Columns Alphabetically

In [ ]:
# print all the data frames to compare and contrast information
#displaying new dataset 1
df1.info()

#displaying new dataset 2
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2149 entries, 0 to 2148
Data columns (total 14 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Age                      2149 non-null   int64
 1   Gender                   2149 non-null   int64
 2   EducationLevel           2149 non-null   int64
 3   Smoking                  2149 non-null   int64
 4   AlcoholConsumption       2149 non-null   float64
 5   PhysicalActivity         2149 non-null   float64
 6   DietQuality              2149 non-null   float64
 7   SleepQuality             2149 non-null   float64
 8   FamilyHistoryAlzheimers  2149 non-null   int64
 9   CardiovascularDisease    2149 non-null   int64
 10  Diabetes                 2149 non-null   int64
 11  Depression               2149 non-null   int64
 12  Hypertension             2149 non-null   int64
 13  Diagnosis                2149 non-null   int64
dtypes: float64(4), int64(10)
memory usage: 235.2 KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 14 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Diabetes               1000 non-null   int64
 1   AlcoholLevel           1000 non-null   float64
 2   Age                    1000 non-null   int64
 3   Education_Level        1000 non-null   object
 4   Gender                 1000 non-null   object
 5   Family_History         1000 non-null   object
 6   Smoking_Status         1000 non-null   object
 7   Physical_Activity      1000 non-null   object
 8   Depression_Status      1000 non-null   object
 9   Nutrition_Diet         1000 non-null   object
 10  Sleep_Quality          1000 non-null   object
 11  Dementia               1000 non-null   int64
 12  Hypertension           1000 non-null   int64
 13  CardiovascularDisease  1000 non-null   int64
dtypes: float64(1), int64(5), object(8)
memory usage: 109.5+ KB

##Cleaning Diet column

In [ ]:
#identify unique values
df2['Nutrition_Diet'].unique()

array(['Low-Carb Diet', 'Mediterranean Diet', 'Balanced Diet'],
      dtype=object)

I am going to classify the mediteranean diet as an 8 because its statistically seen as a very healthy diet.

The Balanced Diet will be given an 7.

And the Low-Carb diet will be given a 6.

This is to allow the diet quality and nutrition_diets to be merged.

This is subjective to debate and I am not a nutritionist, nor do I know the exact rating the other datset used to determine its 1-10 scale rating.

In [ ]:
# Changing Nutrition_Diet to Diet Quality marker
df2['Nutrition_Diet'] = df2['Nutrition_Diet'].replace({
    'Mediterranean Diet': 8,
    'Balanced Diet': 7,
    'Low-Carb Diet': 6
})

/tmp/ipython-input-3923311371.py:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df2['Nutrition_Diet'] = df2['Nutrition_Diet'].replace({

In [ ]:
# Renaming diet column
df2.rename(columns={'Nutrition_Diet': 'DietQuality'}, inplace=True)

##Current Info

In [ ]:
# print all the data frames to compare and contrast information
#displaying new dataset 1
df1.info()

#displaying new dataset 2
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2149 entries, 0 to 2148
Data columns (total 14 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Age                      2149 non-null   int64
 1   Gender                   2149 non-null   int64
 2   EducationLevel           2149 non-null   int64
 3   Smoking                  2149 non-null   int64
 4   AlcoholConsumption       2149 non-null   float64
 5   PhysicalActivity         2149 non-null   float64
 6   DietQuality              2149 non-null   float64
 7   SleepQuality             2149 non-null   float64
 8   FamilyHistoryAlzheimers  2149 non-null   int64
 9   CardiovascularDisease    2149 non-null   int64
 10  Diabetes                 2149 non-null   int64
 11  Depression               2149 non-null   int64
 12  Hypertension             2149 non-null   int64
 13  Diagnosis                2149 non-null   int64
dtypes: float64(4), int64(10)
memory usage: 235.2 KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 14 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Diabetes               1000 non-null   int64
 1   AlcoholLevel           1000 non-null   float64
 2   Age                    1000 non-null   int64
 3   Education_Level        1000 non-null   object
 4   Gender                 1000 non-null   object
 5   Family_History         1000 non-null   object
 6   Smoking_Status         1000 non-null   object
 7   Physical_Activity      1000 non-null   object
 8   Depression_Status      1000 non-null   object
 9   DietQuality            1000 non-null   int64
 10  Sleep_Quality          1000 non-null   object
 11  Dementia               1000 non-null   int64
 12  Hypertension           1000 non-null   int64
 13  CardiovascularDisease  1000 non-null   int64
dtypes: float64(1), int64(6), object(7)
memory usage: 109.5+ KB

##Cleaning Smoking column

In [ ]:
#Getting possibilities for smoking status
df2['Smoking_Status'].unique()

array(['Current Smoker', 'Former Smoker', 'Never Smoked'], dtype=object)

In [ ]:
# Changing status to if someone has ever smoked in there life to binary output
df2['Smoking_Status'] = df2['Smoking_Status'].replace({
    'Current Smoker': 1,
    'Never Smoked': 0,
    'Former Smoker': 1
})

/tmp/ipython-input-2599142669.py:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df2['Smoking_Status'] = df2['Smoking_Status'].replace({

In [ ]:
# Renaming smoking column
df2.rename(columns={'Smoking_Status': 'Smoking'}, inplace=True)

##Cleaning gender column

In [ ]:
# Changing male and female column to 1 = female and 0 = male
df2['Gender'] = df2['Gender'].replace({
    'Female': 1,
    'Male': 0
})

/tmp/ipython-input-3862266842.py:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df2['Gender'] = df2['Gender'].replace({

##Cleaning sleep column

In [ ]:
df2['Sleep_Quality'].unique()

array(['Poor', 'Good'], dtype=object)

In [ ]:
df1['SleepQuality'].unique()

array([9.02567867, 7.15129274, 9.67357416, ..., 5.76946355, 8.32287396,
       9.87871052])

Changing poor sleep to be 4 because that corresponds to the lowest number in the df1, and good sleep to be 8 because that is the hightest number, roughly.

In [ ]:
# Changing sleep status to numeric output
df2['Sleep_Quality'] = df2['Sleep_Quality'].replace({
    'Poor': 4,
    'Good': 8
})

/tmp/ipython-input-4030286583.py:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df2['Sleep_Quality'] = df2['Sleep_Quality'].replace({

In [ ]:
# Renaming sleep column
df2.rename(columns={'Sleep_Quality': 'SleepQuality'}, inplace=True)

##Cleaning physical activity column

In [ ]:
#identifying unique values
df2['Physical_Activity'].unique()

array(['Sedentary', 'Moderate Activity', 'Mild Activity'], dtype=object)

In [ ]:
df1['PhysicalActivity'].unique()

array([6.32711247, 7.61988454, 7.84498779, ..., 9.88600229, 6.35428175,
       6.57099338])

I have decided to label the various activity levels as such.

In [ ]:
# Changing physical activity status to numeric output
df2['Physical_Activity'] = df2['Physical_Activity'].replace({
    'Sedentary': 1,
    'Mild Activity': 4,
    'Moderate Activity': 6,
    'Active': 9
})

/tmp/ipython-input-4085346684.py:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df2['Physical_Activity'] = df2['Physical_Activity'].replace({

In [ ]:
# Renaming physical activity column
df2.rename(columns={'Physical_Activity': 'PhysicalActivity'}, inplace=True)

##Cleaning Family History Column

In [ ]:
df2['Family_History'].unique()

array(['No', 'Yes'], dtype=object)

In [ ]:
# Changing family history status to numeric output
df2['Family_History'] = df2['Family_History'].replace({
    'No': 0,
    'Yes': 1
})

/tmp/ipython-input-1393148501.py:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df2['Family_History'] = df2['Family_History'].replace({

In [ ]:
# Renaming family history column
df2.rename(columns={'Family_History': 'FamilyHistory'}, inplace=True)

##Cleaning Education column

In [ ]:
df2['Education_Level'].unique()

array(['Primary School', 'Secondary School', 'No School',
       'Diploma/Degree'], dtype=object)

In [ ]:
df1['EducationLevel'].unique()

array([2, 0, 1, 3])

In [ ]:
# Changing physical activity status to numeric output
df2['Education_Level'] = df2['Education_Level'].replace({
    'No School': 0,
    'Primary School': 1,
    'Secondary School': 2,
    'Diploma/Degree': 3
})

/tmp/ipython-input-2478306484.py:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df2['Education_Level'] = df2['Education_Level'].replace({

In [ ]:
# Renaming Education column
df2.rename(columns={'Education_Level': 'EducationLevel'}, inplace=True)

##Cleaning Depression column

In [ ]:
df2['Depression_Status'].unique()

array(['No', 'Yes'], dtype=object)

In [ ]:
df1['Depression'].unique()

array([1, 0])

In [ ]:
# Changing depression status to numeric output
df2['Depression_Status'] = df2['Depression_Status'].replace({
    'No': 0,
    'Yes': 1
})

/tmp/ipython-input-2642822626.py:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df2['Depression_Status'] = df2['Depression_Status'].replace({

In [ ]:
# Renaming depression column
df2.rename(columns={'Depression_Status': 'Depression'}, inplace=True)

##Cleaning alcohol level

In [ ]:
df2['AlcoholLevel'].unique()

array([0.08497363, 0.01697277, 0.00900025, 0.08643726, 0.15074731,
       0.1140278 , 0.01619378, 0.16115808, 0.01575425, 0.09733954,
       0.06748564, 0.08267123, 0.02807717, 0.08805155, 0.15656361,
       0.1659716 , 0.03567131, 0.02930638, 0.15908456, 0.19710716,
       0.09234223, 0.08905676, 0.04706498, 0.0022444 , 0.1559942 ,
       0.1055605 , 0.10967133, 0.05261273, 0.1413211 , 0.14555626,
       0.01621965, 0.06240634, 0.1894373 , 0.16636984, 0.13061763,
       0.15008774, 0.08112397, 0.1656683 , 0.09992415, 0.04157571,
       0.10991138, 0.05445505, 0.14617384, 0.19078454, 0.04034117,
       0.07321483, 0.14017791, 0.0227364 , 0.04778358, 0.08807547,
       0.02556337, 0.18617617, 0.04906598, 0.0979699 , 0.10318646,
       0.10808652, 0.16685116, 0.1303138 , 0.15566145, 0.14444342,
       0.04741042, 0.00132653, 0.17627566, 0.03855862, 0.0289448 ,
       0.05047045, 0.07885336, 0.10065803, 0.12261174, 0.12878761,
       0.14539247, 0.12008087, 0.10553423, 0.1484994 , 0.14102849,
       0.08203411, 0.01674517, 0.02715007, 0.0348211 , 0.11560427,
       0.00184745, 0.005932  , 0.18054106, 0.02147929, 0.16457916,
       0.08030365, 0.10988981, 0.1759582 , 0.17693992, 0.17570791,
       0.08378012, 0.00946582, 0.08288708, 0.13266652, 0.01441928,
       0.10657084, 0.02225758, 0.0198375 , 0.02891676, 0.04393754,
       0.12580078, 0.09037909, 0.02861582, 0.09905161, 0.15957816,
       0.07556778, 0.16416662, 0.12492073, 0.0844226 , 0.15823065,
       0.15050143, 0.04211943, 0.16998435, 0.07151079, 0.0981727 ,
       0.18673369, 0.09052328, 0.00538956, 0.18345293, 0.03088041,
       0.16741832, 0.07647675, 0.1310611 , 0.18222672, 0.13293084,
       0.04821314, 0.1418191 , 0.02538527, 0.19841829, 0.10645256,
       0.00596942, 0.18232827, 0.01272682, 0.13631642, 0.00594991,
       0.16385944, 0.00223875, 0.1848945 , 0.02883623, 0.01934973,
       0.1961618 , 0.17522783, 0.00797882, 0.01176313, 0.01505687,
       0.18066483, 0.04138282, 0.08290665, 0.03543642, 0.09345206,
       0.00392742, 0.13983696, 0.00476258, 0.03791121, 0.09066465,
       0.19418159, 0.11000796, 0.06136102, 0.07757214, 0.03492549,
       0.00075123, 0.18032155, 0.18044711, 0.02219116, 0.15610921,
       0.14447184, 0.0651925 , 0.19755788, 0.03321581, 0.16330713,
       0.0885705 , 0.07642647, 0.15093988, 0.05536938, 0.02447235,
       0.0106501 , 0.16596605, 0.10140646, 0.05645235, 0.0770868 ,
       0.10128353, 0.0781569 , 0.10565274, 0.06816146, 0.19868578,
       0.05746055, 0.16386372, 0.09727567, 0.05004333, 0.06778821,
       0.11485823, 0.10391377, 0.08497294, 0.05510572, 0.19307657,
       0.16922436, 0.17118664, 0.14205276, 0.06450613, 0.07540639,
       0.12629525, 0.12636977, 0.04243003, 0.03357462, 0.0677268 ,
       0.1301159 , 0.15183295, 0.11748627, 0.12960695, 0.09829667,
       0.04283118, 0.16421732, 0.16230639, 0.16069884, 0.07477361,
       0.08945871, 0.09456141, 0.13217163, 0.13198044, 0.03364254,
       0.18628435, 0.18670066, 0.07136718, 0.04984119, 0.14470853,
       0.04783472, 0.19468964, 0.05697433, 0.04869155, 0.16479759,
       0.1291697 , 0.01924929, 0.06240857, 0.04270107, 0.00709776,
       0.03335195, 0.03773185, 0.03083237, 0.14126049, 0.01828219,
       0.06786913, 0.06649124, 0.01259572, 0.05264756, 0.12841793,
       0.1500373 , 0.12016918, 0.09935117, 0.15705889, 0.01012653,
       0.13790347, 0.08357977, 0.17917157, 0.17523563, 0.11309612,
       0.17842748, 0.06588146, 0.10702013, 0.15822071, 0.05501179,
       0.13340367, 0.08542795, 0.0356608 , 0.12413804, 0.13268138,
       0.02137562, 0.08345658, 0.08640747, 0.1483371 , 0.13968847,
       0.19026556, 0.01528678, 0.04734405, 0.16165634, 0.02847694,
       0.09522871, 0.19326859, 0.16676958, 0.13602784, 0.19315121,
       0.170115  , 0.11551095, 0.01792819, 0.13249727, 0.08411421,
       0.14695935, 0.03779839, 0.16596689, 0.04215435, 0.11936879,
       0.00813787, 0.02961232, 0.11631408, 0.04103229, 0.06882201,
       0.02262566, 0.1574895 , 0.08845608, 0.13717649, 0.15981092,
       0.0027993 , 0.003053  , 0.12859479, 0.10408379, 0.09036691,
       0.07311244, 0.06492472, 0.14389531, 0.00337746, 0.11751212,
       0.18058351, 0.13294815, 0.15209744, 0.19329944, 0.12902878,
       0.18114046, 0.04194673, 0.1448692 , 0.03162633, 0.17936326,
       0.13694242, 0.10136666, 0.18827965, 0.01899769, 0.04583297,
       0.1558032 , 0.06592655, 0.14759058, 0.16214906, 0.01767465,
       0.09168951, 0.09525035, 0.05812888, 0.12795137, 0.17826269,
       0.08784539, 0.17828747, 0.00601287, 0.18914779, 0.17185552,
       0.10761998, 0.07194594, 0.05157828, 0.04209453, 0.13173519,
       0.17476874, 0.0847893 , 0.12677214, 0.02884559, 0.15671416,
       0.19207943, 0.19747417, 0.07645146, 0.07700663, 0.00469154,
       0.18724753, 0.10774225, 0.11079994, 0.06070961, 0.11054762,
       0.04862339, 0.07556046, 0.11767153, 0.192037  , 0.16348276,
       0.19384233, 0.16523294, 0.05131264, 0.0853888 , 0.0009491 ,
       0.10266206, 0.16932729, 0.19458066, 0.16528735, 0.10426252,
       0.14421929, 0.09086123, 0.07760541, 0.11337275, 0.02544577,
       0.1317878 , 0.13893826, 0.16474016, 0.15912352, 0.15116092,
       0.18007916, 0.10483918, 0.16314296, 0.07184071, 0.07823532,
       0.12460287, 0.02551798, 0.05241862, 0.0988576 , 0.09892813,
       0.09525952, 0.02581265, 0.11817135, 0.1528183 , 0.00992748,
       0.03662827, 0.09016008, 0.11715602, 0.13883896, 0.0468544 ,
       0.10530295, 0.18671868, 0.00041376, 0.18591967, 0.09147516,
       0.06470336, 0.02297896, 0.0240579 , 0.07677538, 0.10554191,
       0.10069805, 0.13405213, 0.00230524, 0.05176344, 0.08248118,
       0.04741246, 0.156452  , 0.17629955, 0.02275356, 0.16411732,
       0.10932601, 0.11500915, 0.01462444, 0.09233913, 0.0606475 ,
       0.1663558 , 0.16266662, 0.04224879, 0.19092564, 0.03909702,
       0.15406771, 0.1945487 , 0.03592285, 0.01310954, 0.10663627,
       0.17697371, 0.16300806, 0.10852263, 0.06990855, 0.00612165,
       0.11185824, 0.18039433, 0.05393278, 0.01702196, 0.04019799,
       0.0340042 , 0.09801116, 0.13678485, 0.00434394, 0.08038423,
       0.09321254, 0.08900674, 0.01260092, 0.01675974, 0.16804437,
       0.18590945, 0.19741269, 0.10131313, 0.15539989, 0.07640258,
       0.10991569, 0.03061773, 0.06135561, 0.19360983, 0.07444584,
       0.03625129, 0.04346641, 0.11987036, 0.17289651, 0.11130611,
       0.07500555, 0.05005697, 0.09630147, 0.06544201, 0.09300563,
       0.00708989, 0.16887556, 0.13304357, 0.00887857, 0.02158902,
       0.12480769, 0.11526732, 0.13648805, 0.08499873, 0.18178175,
       0.11495574, 0.1971682 , 0.02531938, 0.12516003, 0.00567065,
       0.12175831, 0.02226373, 0.10001655, 0.01285921, 0.04555807,
       0.10928299, 0.01445442, 0.09967315, 0.02760778, 0.17911027,
       0.01802406, 0.06110369, 0.0237975 , 0.00122573, 0.15638304,
       0.13920126, 0.07693093, 0.06035764, 0.18507371, 0.12797364,
       0.01186497, 0.10296712, 0.18711567, 0.11882136, 0.12871933,
       0.01462116, 0.15880627, 0.1233428 , 0.14919854, 0.11473695,
       0.01254483, 0.17424377, 0.12820858, 0.02046462, 0.04432624,
       0.12602888, 0.06396599, 0.15828632, 0.05604769, 0.17007383,
       0.16927192, 0.07123392, 0.10142295, 0.00994475, 0.10550379,
       0.15397438, 0.10845718, 0.04635981, 0.01870835, 0.04399313,
       0.13705911, 0.09421628, 0.17698357, 0.14558131, 0.0813488 ,
       0.14064676, 0.17949538, 0.11270154, 0.15380924, 0.09906708,
       0.09672905, 0.08813807, 0.02867192, 0.01548522, 0.17674552,
       0.07007207, 0.14539253, 0.16046714, 0.17603909, 0.02260705,
       0.03602314, 0.15264719, 0.05864244, 0.14986233, 0.02242638,
       0.07282874, 0.19896326, 0.15770846, 0.19787236, 0.03142448,
       0.01225979, 0.19381858, 0.06801304, 0.18991978, 0.02049677,
       0.16997494, 0.00400265, 0.10979044, 0.12796967, 0.16853396,
       0.10890107, 0.03691741, 0.1334113 , 0.13405386, 0.08849696,
       0.16946129, 0.00886579, 0.10609457, 0.16838192, 0.00916858,
       0.07390209, 0.05100162, 0.14077221, 0.14030189, 0.1275875 ,
       0.09137437, 0.15547982, 0.14610966, 0.03669786, 0.18726179,
       0.16690253, 0.07860361, 0.01697132, 0.01768108, 0.02894746,
       0.05893274, 0.09373392, 0.04377511, 0.13223837, 0.15603674,
       0.06171743, 0.14550484, 0.03113737, 0.17235533, 0.19368636,
       0.04105467, 0.10039841, 0.09009544, 0.05134449, 0.16120082,
       0.04682359, 0.19835606, 0.10505   , 0.14987785, 0.02406479,
       0.046913  , 0.06388735, 0.0461122 , 0.17786268, 0.04906079,
       0.16648557, 0.0391715 , 0.16463231, 0.18382551, 0.17420052,
       0.02529223, 0.01985674, 0.01405066, 0.03535762, 0.12647956,
       0.11355337, 0.03066703, 0.13106663, 0.1738438 , 0.07807121,
       0.14076704, 0.10354988, 0.09329878, 0.06914896, 0.16423657,
       0.0669277 , 0.15890592, 0.1704196 , 0.14652373, 0.19879716,
       0.09229951, 0.172895  , 0.10974757, 0.03046104, 0.00896169,
       0.1339038 , 0.15745717, 0.06143619, 0.14192777, 0.08513348,
       0.15178709, 0.02903612, 0.06062926, 0.09720114, 0.07808373,
       0.133204  , 0.18368793, 0.09973036, 0.09608679, 0.18395473,
       0.16861289, 0.19898903, 0.04652902, 0.12159734, 0.06603136,
       0.05599139, 0.02273968, 0.18121016, 0.1943326 , 0.03064807,
       0.00156293, 0.03530612, 0.05358157, 0.15521827, 0.05291089,
       0.01887664, 0.03423298, 0.18405529, 0.14740764, 0.15715726,
       0.10587389, 0.10449083, 0.17542001, 0.07847282, 0.17623404,
       0.15783844, 0.17202831, 0.06475279, 0.17322468, 0.12643596,
       0.02742837, 0.03078668, 0.06801494, 0.07148812, 0.05876521,
       0.16681773, 0.14462864, 0.04882723, 0.08468317, 0.11524516,
       0.09069252, 0.18093973, 0.03266445, 0.02974835, 0.13380648,
       0.17164808, 0.01609181, 0.06175103, 0.08438482, 0.15185962,
       0.08225743, 0.11057348, 0.11124045, 0.13086877, 0.15958522,
       0.02915239, 0.04003091, 0.09749861, 0.02601097, 0.11891909,
       0.01094544, 0.05920255, 0.08140448, 0.18241792, 0.05984286,
       0.06136262, 0.05444419, 0.18708196, 0.17627911, 0.0128184 ,
       0.10881937, 0.00365238, 0.0699965 , 0.15612236, 0.03689728,
       0.18027405, 0.05142228, 0.0218075 , 0.10866156, 0.01542975,
       0.0112142 , 0.13895591, 0.09816468, 0.14133338, 0.10848369,
       0.18632123, 0.12224206, 0.1635444 , 0.12984057, 0.03323184,
       0.04174786, 0.18783326, 0.16643014, 0.12688093, 0.01851334,
       0.00817424, 0.00925325, 0.03896475, 0.11385593, 0.14930051,
       0.128544  , 0.12959603, 0.13930976, 0.18246288, 0.01409859,
       0.18801774, 0.03665432, 0.13058684, 0.01963342, 0.00562937,
       0.05059036, 0.16053171, 0.10777887, 0.04581893, 0.09419707,
       0.05641163, 0.16350577, 0.0015709 , 0.18076088, 0.12619119,
       0.0950365 , 0.15108136, 0.07004668, 0.15170612, 0.07505904,
       0.03894274, 0.03456108, 0.18953471, 0.13568962, 0.08682243,
       0.00833495, 0.13343727, 0.1045809 , 0.17100783, 0.11376029,
       0.07788778, 0.17176224, 0.16595697, 0.13171793, 0.03591735,
       0.19465579, 0.16081819, 0.17623837, 0.02525326, 0.06246854,
       0.15431082, 0.07132213, 0.0533879 , 0.18635168, 0.18206503,
       0.00140011, 0.15922413, 0.06324033, 0.17319668, 0.18816266,
       0.06959869, 0.13056814, 0.19352427, 0.00915555, 0.05790359,
       0.16643792, 0.0076895 , 0.06785172, 0.19561132, 0.0601129 ,
       0.08935815, 0.03740686, 0.16805709, 0.01737589, 0.06426349,
       0.04591177, 0.08702829, 0.15978065, 0.14271626, 0.18332129,
       0.00848272, 0.0866176 , 0.19779866, 0.0353751 , 0.02504547,
       0.18457722, 0.16341432, 0.02100886, 0.03782395, 0.14817207,
       0.18323651, 0.02292898, 0.0527624 , 0.12356741, 0.11243133,
       0.1161194 , 0.04006491, 0.19206964, 0.15535209, 0.10552747,
       0.12470414, 0.08272377, 0.13348241, 0.01590135, 0.05740414,
       0.01039174, 0.03004465, 0.0717515 , 0.18446883, 0.12292055,
       0.19986636, 0.01270315, 0.0111816 , 0.16588645, 0.10543479,
       0.15424782, 0.18352124, 0.18832959, 0.16300982, 0.08625793,
       0.12054622, 0.00492551, 0.03111919, 0.19531668, 0.02396431,
       0.16223035, 0.11979261, 0.16893525, 0.00530924, 0.09021324,
       0.06101016, 0.06298474, 0.13736112, 0.13894536, 0.02397997,
       0.02886247, 0.10368364, 0.03669194, 0.16596466, 0.01013119,
       0.10393844, 0.16740791, 0.16585159, 0.16664306, 0.03312395,
       0.04534544, 0.04356   , 0.12976126, 0.15258266, 0.09839113,
       0.06622261, 0.06569332, 0.07435965, 0.09234921, 0.08881126,
       0.08621462, 0.03253647, 0.04156548, 0.05977683, 0.00346808,
       0.1568024 , 0.16544422, 0.12361477, 0.01746974, 0.09263985,
       0.00305439, 0.15135057, 0.03217626, 0.18724136, 0.14947204,
       0.01787317, 0.16689491, 0.06129733, 0.08390919, 0.00792255,
       0.19063046, 0.17546591, 0.15790411, 0.18909682, 0.05539617,
       0.08401798, 0.14090309, 0.10429969, 0.02244359, 0.13957859,
       0.05985636, 0.06311411, 0.11570705, 0.08113291, 0.01353541,
       0.15029957, 0.01916108, 0.01139818, 0.01499466, 0.17587366,
       0.07867482, 0.05298544, 0.1201309 , 0.05499018, 0.04407096,
       0.01233284, 0.11895637, 0.02641915, 0.1916519 , 0.19557562,
       0.09081696, 0.16684151, 0.1251419 , 0.17202695, 0.10082459,
       0.01749617, 0.03053119, 0.0867111 , 0.07775712, 0.09389002,
       0.01969036, 0.01905627, 0.1394638 , 0.12875235, 0.00272451,
       0.08182465, 0.14524942, 0.07369178, 0.03734723, 0.0859694 ])

In [ ]:
df2['AlcoholLevel'].describe()

count    1000.000000
mean        0.098429
std         0.058715
min         0.000414
25%         0.045505
50%         0.098235
75%         0.151840
max         0.199866
Name: AlcoholLevel, dtype: float64

In [ ]:
df1['AlcoholConsumption'].unique()

array([13.29721773,  4.54252382, 19.55508453, ...,  4.59467018,
        8.67450518,  7.89070315])

I am assuming the original scale of this alcohol is units per week being roughly 20 units max per week. I am going to reverse this so it matches with df1 and is easier for interpretation when modelling.

In [ ]:
df2['AlcoholLevel'] = df2['AlcoholLevel'] / 0.2 * 20

In [ ]:
# Renaming alcohol column
df2.rename(columns={'AlcoholLevel': 'AlcoholConsumption'}, inplace=True)

##Renaming some columns in Dataset 1

In [ ]:
# Renaming diagnosis column
df1.rename(columns={'Diagnosis': 'Dementia'}, inplace=True)
# Renaming family history column
df1.rename(columns={'FamilyHistoryAlzheimers': 'FamilyHistory'}, inplace=True)

##Finalizing Cleaning

I am choosing not to remove any rows with columns that have 0 in them because there are many bianry values.

In [ ]:
#Converting floats to integers, fill any NAN values with 0
#df1
df1['AlcoholConsumption'] = df1['AlcoholConsumption'].fillna(0).astype(int)
df1['DietQuality'] = df1['DietQuality'].fillna(0).astype(int)
df1['PhysicalActivity'] = df1['PhysicalActivity'].fillna(0).astype(int)
df1['SleepQuality'] = df1['SleepQuality'].fillna(0).astype(int)
#df2
df2['AlcoholConsumption'] = df2['AlcoholConsumption'].fillna(0).astype(int)

# Preliminary Exploratory Anlysis

In [ ]:
#sorting columns by alphabet ascending order
df1 = df1.reindex(sorted(df1.columns), axis=1)
df2 = df2.reindex(sorted(df2.columns), axis=1)

In [ ]:
# print all the data frames to compare and contrast information
#displaying new dataset 1
df1.info()

#displaying new dataset 2
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2149 entries, 0 to 2148
Data columns (total 14 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Age                    2149 non-null   int64
 1   AlcoholConsumption     2149 non-null   int64
 2   CardiovascularDisease  2149 non-null   int64
 3   Dementia               2149 non-null   int64
 4   Depression             2149 non-null   int64
 5   Diabetes               2149 non-null   int64
 6   DietQuality            2149 non-null   int64
 7   EducationLevel         2149 non-null   int64
 8   FamilyHistory          2149 non-null   int64
 9   Gender                 2149 non-null   int64
 10  Hypertension           2149 non-null   int64
 11  PhysicalActivity       2149 non-null   int64
 12  SleepQuality           2149 non-null   int64
 13  Smoking                2149 non-null   int64
dtypes: int64(14)
memory usage: 235.2 KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 14 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Age                    1000 non-null   int64
 1   AlcoholConsumption     1000 non-null   int64
 2   CardiovascularDisease  1000 non-null   int64
 3   Dementia               1000 non-null   int64
 4   Depression             1000 non-null   int64
 5   Diabetes               1000 non-null   int64
 6   DietQuality            1000 non-null   int64
 7   EducationLevel         1000 non-null   int64
 8   FamilyHistory          1000 non-null   int64
 9   Gender                 1000 non-null   int64
 10  Hypertension           1000 non-null   int64
 11  PhysicalActivity       1000 non-null   int64
 12  SleepQuality           1000 non-null   int64
 13  Smoking                1000 non-null   int64
dtypes: int64(14)
memory usage: 109.5 KB

In [ ]:
df1.head(10)

,Age,AlcoholConsumption,CardiovascularDisease,Dementia,Depression,Diabetes,DietQuality,EducationLevel,FamilyHistory,Gender,Hypertension,PhysicalActivity,SleepQuality,Smoking
0,73,13,0,0,1,1,1,2,0,0,0,6,9,0
1,89,4,0,0,0,0,0,0,0,0,0,7,7,0
2,73,19,0,0,0,0,1,1,1,0,0,7,9,0
3,74,12,0,0,0,0,7,1,0,1,0,8,8,1
4,89,18,0,0,0,0,0,0,0,0,0,6,5,0
5,86,4,0,0,0,1,1,1,0,1,0,0,7,0
6,68,0,0,0,0,0,5,2,0,0,0,9,5,1
7,75,13,0,1,0,0,8,1,0,0,0,4,4,0
8,72,12,0,0,0,0,6,0,0,1,1,1,5,0
9,87,16,1,0,0,0,8,0,0,0,0,6,7,1

In [ ]:
df2.head(10)

,Age,AlcoholConsumption,CardiovascularDisease,Dementia,Depression,Diabetes,DietQuality,EducationLevel,FamilyHistory,Gender,Hypertension,PhysicalActivity,SleepQuality,Smoking
0,60,8,0,0,0,1,6,1,0,1,0,1,4,1
1,61,1,1,1,0,0,6,2,0,0,0,6,4,1
2,69,0,1,0,0,0,8,1,1,0,0,6,4,1
3,78,8,0,1,1,0,7,2,1,1,1,4,4,0
4,77,15,0,1,0,1,6,2,1,0,0,4,8,0
5,67,11,0,1,1,1,6,0,0,0,0,4,4,1
6,87,1,0,1,0,1,8,1,0,0,0,4,4,0
7,66,16,0,0,0,0,6,2,0,1,1,4,4,1
8,66,1,0,0,0,0,8,2,0,1,0,4,4,1
9,87,9,0,1,1,1,7,3,0,1,0,1,8,1

##Merging the datasets

In [ ]:
#appending df1 and df2
merged_df = pd.concat([df1, df2], axis=0, ignore_index=True)

In [ ]:
#adding PatientID starting at 0
merged_df['PatientID'] = range(len(merged_df))

In [ ]:
merged_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3149 entries, 0 to 3148
Data columns (total 15 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Age                    3149 non-null   int64
 1   AlcoholConsumption     3149 non-null   int64
 2   CardiovascularDisease  3149 non-null   int64
 3   Dementia               3149 non-null   int64
 4   Depression             3149 non-null   int64
 5   Diabetes               3149 non-null   int64
 6   DietQuality            3149 non-null   int64
 7   EducationLevel         3149 non-null   int64
 8   FamilyHistory          3149 non-null   int64
 9   Gender                 3149 non-null   int64
 10  Hypertension           3149 non-null   int64
 11  PhysicalActivity       3149 non-null   int64
 12  SleepQuality           3149 non-null   int64
 13  Smoking                3149 non-null   int64
 14  PatientID              3149 non-null   int64
dtypes: int64(15)
memory usage: 369.2 KB

In [ ]:
merged_df.head(10)

,Age,AlcoholConsumption,CardiovascularDisease,Dementia,Depression,Diabetes,DietQuality,EducationLevel,FamilyHistory,Gender,Hypertension,PhysicalActivity,SleepQuality,Smoking,PatientID
0,73,13,0,0,1,1,1,2,0,0,0,6,9,0,0
1,89,4,0,0,0,0,0,0,0,0,0,7,7,0,1
2,73,19,0,0,0,0,1,1,1,0,0,7,9,0,2
3,74,12,0,0,0,0,7,1,0,1,0,8,8,1,3
4,89,18,0,0,0,0,0,0,0,0,0,6,5,0,4
5,86,4,0,0,0,1,1,1,0,1,0,0,7,0,5
6,68,0,0,0,0,0,5,2,0,0,0,9,5,1,6
7,75,13,0,1,0,0,8,1,0,0,0,4,4,0,7
8,72,12,0,0,0,0,6,0,0,1,1,1,5,0,8
9,87,16,1,0,0,0,8,0,0,0,0,6,7,1,9

##Saving data frames to csv files

In [ ]:
# Save df1
df1.to_csv('/content/df1_clean.csv', index=False)

# Save df2
df2.to_csv('/content/df2_clean.csv', index=False)

# If you have a merged dataset
merged_df.to_csv('/content/merged_df.csv', index=False)

##Entire merged data frame

In [ ]:
merged_df

,Age,AlcoholConsumption,CardiovascularDisease,Dementia,Depression,Diabetes,DietQuality,EducationLevel,FamilyHistory,Gender,Hypertension,PhysicalActivity,SleepQuality,Smoking,PatientID
0,73,13,0,0,1,1,1,2,0,0,0,6,9,0,0
1,89,4,0,0,0,0,0,0,0,0,0,7,7,0,1
2,73,19,0,0,0,0,1,1,1,0,0,7,9,0,2
3,74,12,0,0,0,0,7,1,0,1,0,8,8,1,3
4,89,18,0,0,0,0,0,0,0,0,0,6,5,0,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3144,88,8,0,1,0,1,7,3,1,0,0,4,4,0,3144
3145,80,14,0,0,0,1,6,1,0,1,0,6,4,0,3145
3146,67,7,0,0,0,1,7,1,0,1,0,1,8,0,3146
3147,62,3,0,1,1,0,6,0,1,0,0,1,8,0,3147
3148,80,8,1,0,0,0,8,2,1,1,0,4,8,0,3148

# Train Test Split

# Training Models

# Going Further

# Conclusion and Discussion